name: CI

on: push

jobs:
 deploy:
     runs-on: ubuntu-latest
     environment: Production
     steps:
       - uses: actions/checkout@v4
       - name: Depoly
         env:
           TOKEN: ${{ secrets.DEPLOY_TOKEN }}
         run: echo "Deploying to production"
